"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import StoreProvider from "@/app/store/StoreProvider";
import Head from "next/head";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [screenWidth, setScreenWidth] = useState(0);

  useEffect(() => {
    // Function to update screenWidth state
    const updateScreenWidth = () => {
      setScreenWidth(window.innerWidth);
    };

    // Add event listener to update screenWidth on resize
    window.addEventListener("resize", updateScreenWidth);

    // Initial call to set screenWidth on component mount
    updateScreenWidth();

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener("resize", updateScreenWidth);
    };
  }, []);

  return (
    <StoreProvider>
      <html lang="en">
        {/* <Head>
          <link
            rel="icon"
            href="/public/Layer_1 (10).svg"
            sizes="32x32"
            type="image/svg+xml"
          />
        </Head> */}
        <body className={inter.className} id={screenWidth < 500 ? "body" : ""}>
          <Nav />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
